name: newsite1
favicon: null
layout_spectrum: 0.45357600902207196
typography_spectrum: 0.8738288676831871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1908491135109216
  lightness: 0.11580872489139438
  saturation: 0.9075838075950742
  rhythmicContrast: 0.6544481641612947
purpose: []
